apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: task-manager-api
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: task-manager-api

  template:
    metadata:
      labels:
        app: task-manager-api

    spec:
      containers:
        - name: task-manager-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 8080

          # --- Environment Variables ---
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "local"

            # Disable Redis cache in EKS for now
            - name: SPRING_CACHE_TYPE
              value: "none"

            - name: SERVER_PORT
              value: "8080"

          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}

          # --- Liveness Probe ---
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3

          # --- Readiness Probe ---
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

