apiVersion: v1
kind: Service
metadata:
  name: task-manager-api
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}

  selector:
    app: task-manager-api

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP

