replicaCount: 2

image:
  repository: aisalkyn85/task-manager-api
  tag: "6"
  pullPolicy: Always

springProfile: "prod"

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

